spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/d20dashboard}
    username: ${SPRING_DATASOURCE_USERNAME:d20user}
    password: ${SPRING_DATASOURCE_PASSWORD:d20pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect